services:
  hailo-env:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        ENABLE_SSH: "true"
    image: hailo-env:local
    container_name: hailo_env
    restart: unless-stopped
    shm_size: "512mb"
    privileged: true
    devices:
      - /dev/hailo0:/dev/hailo0
    volumes:
      - /var/run/hailo:/var/run/hailo
      - /etc/localtime:/etc/localtime:ro
      - ./volumes/root:/root
    ports:
      - "8222:22"
      - "8000:8000"
